---

- include: "postgresql/add/repository.yml"
  tags:    [postgresql, add, repository]

- include: "postgresql/add/apt/key.yml"
  tags:    [postgresql, add, apt, key]

- include: "postgresql/install/package.yml"
  tags:    [postgresql, install, package]

