---

- name: "postgresql:install:apt:package | Installing the apt package."
  apt:
    name:             '{{ item.package }}'
    state:            "latest"
  #  update_cache:     '{{ item.cache_update }}'
  #  cache_valid_time: '{{ item.cache_ttl }}'
  with_items:
    - '{"package": "{{ postgresql_apt_package }}", "cache_update": "{{ postgresql_apt_cache_update }}", "cache_ttl": "{{ postgresql_apt_cache_timeout }}"}'

